name: Build and Push Docker Image

on:
  push:
    branches:
      - main
# agregando el workflow para que se ejecute en cada push a la rama main
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Set up Docker Buildx
        run: | 
          docker build -t minginx:latest .

      - name: Login and push to Docker Hub
        run: |
          docker login -u elsoloeres -p  ${{ secrets.TOKEN_DOCKER_HUB }}
          docker tag minginx:latest elsoloeres/minginx:latest
          docker push elsoloeres/minginx:latest
      - name: ssh scp ssh pipelines
        uses: cross-the-world/ssh-scp-ssh-pipelines@latest
        env:
          WELCOME: "ssh scp ssh pipelines"
          LASTSSH: "Doing something after copying"
        with:
          host: ${{ secrets.SERVER_HOST }}
          user: ${{ secrets.SERVER_USER }}
          pass: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          connect_timeout: 10s
          first_ssh: |
            docker pull elsoloeres/minginx:latest
            cd /root/github-docker
            docker compose up -d